#Put your address in here... so you don't have to check it in
#This is not my real address.  Drop me a message on github if you need
#my contact info
address: "12 Hammond Road \\\Woking, Surrey, GU21 4TQ\\\(+44) 7967189579\\\julian@juliansimpson.org"
